"""Collection of the production rules of context-free grammar of regular experssion string."""

rules = {
    'top': [
        ['empty'],
        ['single'],
        ['union'],
        ['concatenation'],
        ['kleene'],
    ],
   
    'empty': [
        ['.'],
    ],
    
    'single': [
        ['a'],
        ['b'],
        ['c'],
        ['d'],
        ['e'],
        ['f'],
        ['g'],
        ['h'],
        ['i'],
        ['j'],
        ['k'],
        ['l'],
        ['m'],
        ['n'],
        ['o'],
        ['p'],
        ['q'],
        ['r'],
        ['s'],
        ['t'],
        ['u'],
        ['v'],
        ['w'],
        ['x'],
        ['y'],
        ['z'],
        ['A'],
        ['B'],
        ['C'],
        ['D'],
        ['E'],
        ['F'],
        ['G'],
        ['H'],
        ['I'],
        ['J'],
        ['K'],
        ['L'],
        ['M'],
        ['N'],
        ['O'],
        ['P'],
        ['Q'],
        ['R'],
        ['S'],
        ['T'],
        ['U'],
        ['V'],
        ['W'],
        ['X'],
        ['Y'],
        ['Z'],
        ['0'],
        ['1'],
        ['2'],
        ['3'],
        ['4'],
        ['5'],
        ['6'],
        ['7'],
        ['8'],
        ['9'],
    ],
    
    'union': [
        ['empty', '|', 'empty'],
        ['empty', '|', 'single'],
        ['empty', '|', 'union'],
        ['empty', '|', 'concatenation'],
        ['empty', '|', 'kleene'],
        ['single', '|', 'empty'],
        ['single', '|', 'single'],
        ['single', '|', '(', 'union', ')'],
        ['single', '|', 'concatenation'],
        ['single', '|', 'kleene'],
        ['(', 'union', ')', '|', 'empty'],
        ['(', 'union', ')', '|', 'single'],
        ['(', 'union', ')', '|', '(', 'union', ')'],
        ['(', 'union', ')', '|', 'concatenation'],
        ['(', 'union', ')', '|', 'kleene'],
        ['concatenation', '|', 'empty'],
        ['concatenation', '|', 'single'],
        ['concatenation', '|', '(', 'union', ')'],
        ['concatenation', '|', 'concatenation'],
        ['concatenation', '|', 'kleene'],
        ['kleene', '|', 'empty'],
        ['kleene', '|', 'single'],
        ['kleene', '|', '(', 'union', ')'],
        ['kleene', '|', 'concatenation'],
        ['kleene', '|', 'kleene'],
    ],
    
    'concatenation': [
        ['empty', 'empty'],
        ['empty', 'single'],
        ['empty', '(', 'union', ')'],
        ['empty', 'concatenation'],
        ['empty', 'kleene'],
        ['single', 'empty'],
        ['single', 'single'],
        ['single', '(', 'union', ')'],
        ['single', 'concatenation'],
        ['single', 'kleene'],
        ['(', 'union', ')', 'empty'],
        ['(', 'union', ')', 'single'],
        ['(', 'union', ')', '(', 'union', ')'],
        ['(', 'union', ')', 'concatenation'],
        ['(', 'union', ')', 'kleene'],
        ['concatenation', 'empty'],
        ['concatenation', 'single'],
        ['concatenation', '(', 'union', ')'],
        ['concatenation', 'concatenation'],
        ['concatenation', 'kleene'],
        ['kleene', 'empty'],
        ['kleene', 'single'],
        ['kleene', '(', 'union', ')'],
        ['kleene', 'concatenation'],
        ['kleene', 'kleene'],
    ],
    
    'kleene': [
        ['empty', '*'],
        ['single', '*'],
        ['(', 'union', ')', '*'],
        ['(', 'concatenation', ')', '*'],
        ['kleene', '*'],
    ]
}
